task_name: [BBBP,BACE,ClinTox,FreeSolv,ESOL,Lipo, ZhangDDI, ChChMiner, DeepDDI]
eval_every_n_epochs: 1
log_every_n_steps: 50
fp16_precision: False
epochs: 100
batch_size: 32
init_base_lr: 0.0001
weight_decay: 1e-6
dataset:
  task: None
  data_path: None
  target: None
target_list: []
t5_ckpt_path: None

